export const metadata = {
  title: {
    template: 'Nest.js | $s',
    default: 'loading..'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
